# Generated by Django 6.0.2 on 2026-02-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('img_url', models.TextField(blank=True)),
                ('search_url', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('checkin', models.CharField(blank=True, max_length=50)),
                ('checkout', models.CharField(blank=True, max_length=50)),
                ('guests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
